### ISSUE TITLE
P2P networking status

### ISSUE THREAD

**Issue by slothbag** [richardschneider/net-ipfs-core#18]
This is looking great.. I see there is a NetworkProtocol class.. how close is this to serving up content over the P2P network?

Really looking forward to a c# implementation of IPFS

**Comment by richardschneider** [comment]
Thanks for the +1.  I haven't spent much time on this lately.  I'll get back to you with a current status.

**Comment by slothbag** [comment]
I expect translating the DHT and BitSwap protocols would be quite a large piece of work..

However, i'd love a minimal implementation that can serve up content/blocks on request (that it has).  Not sure how much of the DHT and BitSwap that would require.

**Comment by slothbag** [comment]
I'll just be happy with a working library at the moment :)
