### ISSUE TITLE
MultiHash.ComputeHash

### ISSUE THREAD

**Issue by supertoha** [richardschneider/net-ipfs-core#20]
It looks like MultiHash.ComputeHash(byte[] data, algorithmName="sha2-256") method
works incorrect.

just check it. Steps:
1)implement a test:
var dataFomWeb = new WebClient().DownloadData("https://ipfs.io/ipfs/QmRACojSdFuqnyyfQZ9Zgiz6zrVCUX1JRkYZyvRGu1MCzG");
 var hash = MultiHash.ComputeHash(dataFomWeb);
Console.WriteLine(hash.ToBase58());
// result "QmRK2JUQta8mgh2m8mp63vv6YCRDc1Z27GV35LRUQtABNN"

2) comapare result. 
QmRK2JUQta8mgh2m8mp63vv6YCRDc1Z27GV35LRUQtABNN and
QmRACojSdFuqnyyfQZ9Zgiz6zrVCUX1JRkYZyvRGu1MCzG are not equal

Why?

**Comment by richardschneider** [comment]
I'm moving this weekend so will get back  to u next week.  Thanks for the
bug report

**Comment by slothbag** [comment]
The reason for this is because the link used is a merkeld-dag link.. whereas the multihash computed in your code is just the raw data of the file, without the merkel-dag wrapper.
