### ISSUE TITLE
Empty multibase strings are valid

### ISSUE THREAD

**Issue by Stebalien** [richardschneider/net-ipfs-core#34]
That is, strings consisting only of a multibase prefix. This library currently forbids them https://github.com/richardschneider/net-ipfs-core/commit/c18388ec1ab2f8ba262a730084c82deff5ebc10c#diff-b8ca87d909bbb86b73fc6f2d46dfd0ddR94

**Comment by richardschneider** [comment]
Good catch! Thanks @Stebalien

**Comment by richardschneider** [comment]
Fixed in release [v0.16.0](https://github.com/richardschneider/net-ipfs-core/releases/tag/v0.16.0)
