### ISSUE TITLE
Hash examples

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/net-ipfs-core#66]
https://github.com/multiformats/website/blob/master/content/multihash.md now has examples for some hashes.  Create a unit test to verify.

**Comment by mosinms7711** [comment]
Hello…I am creating hash value for image with multi hash and i am adding same image to ipfs but both hash values are different…???so can anyone pleasse help with this...

**Comment by richardschneider** [comment]
@mosinms7711 Please give an example.

Note that `ipfs add image.jpeg` produces a hash of the dag-pb block(s) not just the hash of image.jpeg.  See [comment](https://github.com/richardschneider/net-ipfs-core/issues/20#issuecomment-198233029) by @slothbag

**Comment by mosinms7711** [comment]
@richardschneider  For example if there is image with name funImage.png...when we add it to IPFS then it gives me "**QmXExS4BMc1YrH6iWERyryFcDWkvobxryXSwECLrcd7Y1H**" and when i am creating hash value with multihash for same image it gives me "**QmaZNJC2WexKbjiBaTuSjsGrx3keNJgPZQC9Rbdm24pU8x**"...now i want to create same hash value for both...

**Comment by richardschneider** [comment]
You are comparing apples and oranges.

The `ipfs add` command wraps the data in a [merkle dag](https://github.com/ipfs/specs/blob/master/merkledag/README.md) and then takes a hash of it.

Try `ipfs block put funImage.png`, which adds the raw data **WITHOUT**  the `merkle dag`. The returned hash is now **QmaZNJC2WexKbjiBaTuSjsGrx3keNJgPZQC9Rbdm24pU8x** !!!

**Comment by richardschneider** [comment]
@mosinms7711 You could help this project by adding the [test vectors](https://github.com/multiformats/website/blob/master/content/multihash.md) to the [multihash unit test](https://github.com/richardschneider/net-ipfs-core/blob/master/test/MultiHashTest.cs#L297)

**Comment by mosinms7711** [comment]
@richardschneider  i will check that...Please tell me one thing how to add ipfs.core nuget in android project with xamarin forms and what is dependancy required for the same.
